### PR TITLE
Redux devtools trace + source map

### PR DESCRIPTION
**Pull request by StanislavMayorov**
I've added source map fix to this trace implementation https://github.com/jhen0409/react-native-debugger/pull/301 and removed `RNDebuggerWorker.js` lines from stack trace. So now the feature works fine.
I logged performance of `updateStackWithSourceMap ` parser. It takes only about 0.07 millisecond for each action. Entire `getStackTrace ` takes about 0.4 millisecond. 
Redux devtools trace tab render are slow, it's even worse than in web apps. I tested it in a big app and It took more than 5 sec, but I don't think that we can improve it. 
Open file feature doesn't work.

### CODE REVIEW

**Comment by StanislavMayorov** [comment]
@jhen0409 How to pass custom [openFile props](https://github.com/reduxjs/redux-devtools/pull/458) to `StackTraceTab` ?

**Comment by StanislavMayorov** [comment]
@jhen0409 could you take a look at the PR please?

**Comment by jhen0409** [comment]
> Redux devtools trace tab render are slow, it's even worse than in web apps. I tested it in a big app and It took more than 5 sec, but I don't think that we can improve it.

I see that it will take a few seconds to fetch / parse the source map on app. https://github.com/jhen0409/react-native-debugger/commit/dabd2ae76a27152b8e0ddaa05e1cc96e6c2247d1 caused it to re-fetch every time.

> @jhen0409 How to pass custom openFile props to StackTraceTab ?

Currently, it is no way to pass the prop to [`inspector`](https://github.com/reduxjs/redux-devtools/blob/master/packages/redux-devtools-inspector/src/ActionPreview.jsx#L71), it still needs some work. Or we can just patch it with [patch-package](https://www.npmjs.com/package/patch-package) for `openFile` of `redux-devtools-trace-monitor`. (Use [`window.openInEditor`](https://github.com/jhen0409/react-native-debugger/blob/master/app/index.js#L60))

**Comment by StanislavMayorov** [comment]
> I see that it will take a few seconds to fetch / parse the source map on app. dabd2ae caused it to re-fetch every time.

That's interesting. Do you know if it's possible to clean cache once on reload (for example ses.clearCache) in the future?

> Currently, it is no way to pass the prop to [`inspector`](https://github.com/reduxjs/redux-devtools/blob/master/packages/redux-devtools-inspector/src/ActionPreview.jsx#L71), it still needs some work. Or we can just patch it with [patch-package](https://www.npmjs.com/package/patch-package) for `openFile` of `redux-devtools-trace-monitor`. (Use [`window.openInEditor`](https://github.com/jhen0409/react-native-debugger/blob/master/app/index.js#L60))

I will try to fix using patch-package for now. Thank you.

**Comment by StanislavMayorov** [comment]
> Or we can just patch it with [patch-package](https://www.npmjs.com/package/patch-package) for `openFile` of `redux-devtools-trace-monitor`. (Use [`window.openInEditor`](https://github.com/jhen0409/react-native-debugger/blob/master/app/index.js#L60))

I've added the patch to open file. It works fine and it's possible to select an editor in settings. Can you merge it please? 
I will try to create a PR to redux-devtools-inspector later to get rid of the patch.

> I see that it will take a few seconds to fetch / parse the source map on app. [dabd2ae](https://github.com/jhen0409/react-native-debugger/commit/dabd2ae76a27152b8e0ddaa05e1cc96e6c2247d1) caused it to re-fetch every time.
> 
> >

I tested without `app.commandLine.appendSwitch('disable-http-cache');` and it was 20-30% faster, but still slow.

**Comment by StanislavMayorov** [comment]
@jhen0409 I added open file feature. Could you merge the PR please?

**Comment by jhen0409** [comment]
Thanks for PR, and sorry for delay. This will be released soon in next few days.

**Pull request merged**
