### PR TITLE
Upgrade react-devtools-core to v4

### PR DESCRIPTION
**Pull request by jhen0409**
Upgrade `react-devtools-core` to v4. ([`facebook/react/tree/master/packages/react-devtools-core`](https://github.com/facebook/react/tree/master/packages/react-devtools-core))

The new backend and global hook is not backward compatible, but currently it's haven't any versions of React Native used that.

## TODO

~- [ ] `devtools.setDefaultThemeName`~
- [x] Remove `setDefaultThemeName` usage
- [x] Documentation update
- [x] Remove React Native version < 0.62 support

### CODE REVIEW

**Comment by jhen0409** [comment]
How to test it in current React Native projects:

- Install dependency `react-devtools-core@4.0.0-alpha.0` in your app, and add to `resolutions`

```js
{
  ...
  "devDependencies": {
    "react-devtools-core": "4.0.0-alpha.0"
  },
  "resolutions": {
    "react-devtools-core": "4.0.0-alpha.0"
  },
  ...
}
```

- Patch the `node_modules/react-native/Libraries/Inspector/Inspector.js` file with https://github.com/bvaughn/react-devtools-experimental/issues/334#issuecomment-513480685

**Comment by bvaughn** [comment]
Hi @jhen_jie :wave:

Just a quick update to let you know that:
* I published a new stable version of v3 (frontend) that detects a v4 backend and shows an upgrade prompt. Might be worth updating your current version of react-native-debugger to react-devtools-core@3.6.2 just in case someone connects a newer version of React Native to an older version of react-native-debugger.
* I published a new v4 alpha today (alpha 3) with a bunch of small bug fixes and UI/UX improvements.

**Comment by msand** [comment]
@bvaughn What do I need to do to make the dimensions of elements to show up correctly in the debugger, when using react-native-svg? (I'm the maintainer) 
It used to work, but seems broken nowadays.

**Comment by msand** [comment]
Seems it's only broken on android btw, ios works correctly.

**Comment by msand** [comment]
If you start the debugger and enable the inspector, then when you select/hover an element in the Elements pane it highlights the element in the simulator/emulator, or if you click and element in the simulator then it selects it in the debugger, correct behavior can be seen with ios as in the example screenshot.

But, android only highlights the entire svg root element even if an ancestor is selected so it's not very easy to debug placement/transform/bounds related issues. Seems the javascript side doesn't get the dimensions from the native side correctly for some reason. Has anything changed with how that is communicated from native to the debugger/js side, or how it's requested by js from the native side?

App.js
```jsx
import React from 'react';
import {Svg, Rect} from 'react-native-svg';

export default () => (
  <Svg width="100%" height="100%" viewBox="0 0 100 100">
    <Rect x="10" y="10" width="30" height="30" fill="green" />
    <Rect x="60" y="60" width="30" height="30" fill="green" />
  </Svg>
);

```

Screen Shot 2019-08-27 at 20 49 53

**Comment by msand** [comment]
@bvaughn True, I realize now the issue is actually independent of the debugger, as the inspector should be enough to be able to select/inspect elements. Not sure what would be the correct place to discuss it, any suggestion?

**Pull request merged**
