### PR TITLE
Refactor `Toggle Device Sync` feature

### PR DESCRIPTION
**Pull request by jhen0409**
Other changes:

- Fix: `this.props.debugger.syncState` -> `this.props.actions.debugger.syncState`
- default value of sync state: `true` -> `false`
- Menu item `Toggle Device Sync` is now as checkbox

### CODE REVIEW

**Comment by jamesreggio** [comment]
Is there any way to decouple the `this.props.debugger.syncState -> this.props.actions.debugger.syncState` fix and release sooner? It's making debugging on Android nearly impossible for me.

**Comment by jhen0409** [comment]
It's ready to merge, sorry for delay! 😅

**Comment by jamesreggio** [comment]
Thanks @jhen0409 — would be great to get a release, too :)

**Comment by EskelCz** [comment]
I can't find any documentation on this feature. What does it do?

**Comment by varemenos** [comment]
@jhen0409 I just wanted to point out that enabling this feature somehow makes the debugger fetch sourcemaps (visibly) faster. I used to wait 2-3 seconds while the debugger was frozen while preparing (or fetching, not sure what's happening behind the scenes) the sourcemaps. After turning this feature on, the waiting time is at most 1 second!

Is there anything provided by this feature that could accomplish such a thing? If yes, maybe it's possible to bring this optimization to the debugger when device sync is disabled as well.

Sorry, I noticed this and didn't know where to mention it, I thought it made sense to post it under a merged PR with the name of the feature.

**Pull request merged**
